'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'zh';

interface AdminLanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    dashboard: 'Dashboard',
    content: 'Content',
    users: 'Users',
    settings: 'Settings',
    logout: 'Logout',
    welcome: 'Welcome back',
    totalEdits: 'Total Edits',
    lastUpdated: 'Last Updated',
    activeUsers: 'Active Users',
    pendingReviews: 'Pending Reviews',
    heroSection: 'Hero Section',
    aboutSection: 'About Section',
    servicesSection: 'Services Section',
    contactSection: 'Contact Section',
    footerSection: 'Footer Section',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    lastLogin: 'Last Login',
    title: 'Title',
    description: 'Description',
    image: 'Image',
    uploadImage: 'Upload Image',
    contactInfo: 'Contact Information',
    socialLinks: 'Social Links',
    phone: 'Phone',
    address: 'Address',
    facebook: 'Facebook',
    twitter: 'Twitter',
    instagram: 'Instagram',
    linkedin: 'LinkedIn',
    login: 'Login',
    password: 'Password',
    rememberMe: 'Remember me',
    // Dashboard specific
    welcomeToDashboard: 'to your admin dashboard',
    recentActivity: 'Recent Activity',
    contentOverview: 'Content Overview',
    systemStatus: 'System Status',
    fromLastMonth: 'from last month',
    thisWeek: 'this week',
    updatedHeroSection: 'Updated Hero Section',
    modifiedAboutSection: 'Modified About Section',
    addedNewService: 'Added new service',
    updatedContactInfo: 'Updated contact info',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    by: 'by',
    admin: 'Admin',
    editor: 'Editor',
    heroSections: 'Hero Sections',
    aboutSections: 'About Sections',
    services: 'Services',
    projects: 'Projects',
    database: 'Database',
    healthy: 'Healthy',
    apiStatus: 'API Status',
    online: 'Online',
    storage: 'Storage',
    used: 'Used',
    cache: 'Cache',
    optimized: 'Optimized',
    // Login page
    loginToDashboard: 'to access the dashboard',
    loggingIn: 'Logging in...',
    invalidCredentials: 'Invalid credentials',
    errorOccurred: 'An error occurred. Please try again.',
    protectedArea: 'Protected admin area - Authorized access only',
    // Content page
    manageContent: 'Manage your website content across multiple languages',
    contentLanguage: 'Content Language',
    selectLanguage: 'Select the language you want to edit',
    lastEdited: 'Last edited',
    subtitle: 'Subtitle',
    buttonText: 'Button Text',
    enterTitle: 'Enter title...',
    enterSubtitle: 'Enter subtitle...',
    enterDescription: 'Enter description...',
    enterButtonText: 'Enter button text...',
    noImageUploaded: 'No image uploaded',
    upload: 'Upload',
    remove: 'Remove',
    unsavedChanges: 'Unsaved changes',
    saveChanges: 'Save Changes',
    changes: 'Changes',
    // Users page
    manageUsers: 'Manage user accounts and permissions',
    addUser: 'Add User',
    totalUsers: 'Total Users',
    admins: 'Admins',
    searchUsers: 'Search users...',
    filters: 'Filters',
    actions: 'Actions',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    noUsersFound: 'No users found',
    viewer: 'Viewer',
    // Settings page
    manageSettings: 'Manage your application settings and preferences',
    updateContactInfo: 'Update your business contact information',
    manageSocialMedia: 'Manage your social media profiles',
    globalSettings: 'Global Settings',
    configureSystem: 'Configure system-wide preferences',
    maintenanceMode: 'Maintenance Mode',
    maintenanceModeDesc: 'Enable maintenance mode to prevent user access',
    emailNotifications: 'Email Notifications',
    emailNotificationsDesc: 'Receive email notifications for important events',
    twoFactorAuth: 'Two-Factor Authentication',
    twoFactorAuthDesc: 'Require 2FA for all admin users',
    publicRegistration: 'Public Registration',
    publicRegistrationDesc: 'Allow new users to register accounts',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    content: 'المحتوى',
    users: 'المستخدمون',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    welcome: 'مرحباً بك',
    totalEdits: 'إجمالي التعديلات',
    lastUpdated: 'آخر تحديث',
    activeUsers: 'المستخدمون النشطون',
    pendingReviews: 'المراجعات المعلقة',
    heroSection: 'القسم الرئيسي',
    aboutSection: 'قسم من نحن',
    servicesSection: 'قسم الخدمات',
    contactSection: 'قسم التواصل',
    footerSection: 'قسم التذييل',
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    name: 'الاسم',
    email: 'البريد الإلكتروني',
    role: 'الدور الوظيفي',
    lastLogin: 'آخر تسجيل دخول',
    title: 'العنوان',
    description: 'الوصف',
    image: 'الصورة',
    uploadImage: 'رفع صورة',
    contactInfo: 'معلومات التواصل',
    socialLinks: 'روابط وسائل التواصل',
    phone: 'رقم الهاتف',
    address: 'العنوان',
    facebook: 'فيسبوك',
    twitter: 'تويتر',
    instagram: 'إنستغرام',
    linkedin: 'لينكد إن',
    login: 'تسجيل الدخول',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    // Dashboard specific
    welcomeToDashboard: 'في لوحة التحكم الخاصة بك',
    recentActivity: 'النشاطات الأخيرة',
    contentOverview: 'نظرة عامة على المحتوى',
    systemStatus: 'حالة النظام',
    fromLastMonth: 'من الشهر الماضي',
    thisWeek: 'هذا الأسبوع',
    updatedHeroSection: 'تحديث القسم الرئيسي',
    modifiedAboutSection: 'تعديل قسم من نحن',
    addedNewService: 'إضافة خدمة جديدة',
    updatedContactInfo: 'تحديث معلومات التواصل',
    hoursAgo: 'منذ ساعات',
    daysAgo: 'منذ أيام',
    by: 'بواسطة',
    admin: 'مدير',
    editor: 'محرر',
    heroSections: 'الأقسام الرئيسية',
    aboutSections: 'أقسام من نحن',
    services: 'الخدمات',
    projects: 'المشاريع',
    database: 'قاعدة البيانات',
    healthy: 'جيدة',
    apiStatus: 'حالة الـ API',
    online: 'متصل',
    storage: 'التخزين',
    used: 'مستخدم',
    cache: 'الذاكرة المؤقتة',
    optimized: 'محسنة',
    // Login page
    loginToDashboard: 'للوصول إلى لوحة التحكم',
    loggingIn: 'جاري تسجيل الدخول...',
    invalidCredentials: 'بيانات دخول غير صحيحة',
    errorOccurred: 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    protectedArea: 'منطقة إدارية محمية - الوصول للمصرح لهم فقط',
    // Content page
    manageContent: 'إدارة محتوى موقعك الإلكتروني بجميع اللغات',
    contentLanguage: 'لغة المحتوى',
    selectLanguage: 'اختر اللغة التي تريد تحريرها',
    lastEdited: 'آخر تعديل',
    subtitle: 'العنوان الفرعي',
    buttonText: 'نص الزر',
    enterTitle: 'أدخل العنوان...',
    enterSubtitle: 'أدخل العنوان الفرعي...',
    enterDescription: 'أدخل الوصف...',
    enterButtonText: 'أدخل نص الزر...',
    noImageUploaded: 'لم يتم رفع صورة',
    upload: 'رفع',
    remove: 'إزالة',
    unsavedChanges: 'تغييرات غير محفوظة',
    saveChanges: 'حفظ التغييرات',
    changes: 'التغييرات',
    // Users page
    manageUsers: 'إدارة حسابات المستخدمين والصلاحيات',
    addUser: 'إضافة مستخدم',
    totalUsers: 'إجمالي المستخدمين',
    admins: 'المدراء',
    searchUsers: 'البحث عن مستخدمين...',
    filters: 'تصفية',
    actions: 'الإجراءات',
    status: 'الحالة',
    active: 'نشط',
    inactive: 'غير نشط',
    noUsersFound: 'لم يتم العثور على مستخدمين',
    viewer: 'مشاهد',
    // Settings page
    manageSettings: 'إدارة إعدادات التطبيق والتفضيلات',
    updateContactInfo: 'تحديث معلومات التواصل الخاصة بعملك',
    manageSocialMedia: 'إدارة ملفات التواصل الاجتماعي',
    globalSettings: 'الإعدادات العامة',
    configureSystem: 'تكوين التفضيلات على مستوى النظام',
    maintenanceMode: 'وضع الصيانة',
    maintenanceModeDesc: 'تفعيل وضع الصيانة لمنع وصول المستخدمين',
    emailNotifications: 'إشعارات البريد الإلكتروني',
    emailNotificationsDesc: 'تلقي إشعارات البريد الإلكتروني للأحداث الهامة',
    twoFactorAuth: 'المصادقة الثنائية',
    twoFactorAuthDesc: 'طلب المصادقة الثنائية لجميع مستخدمي الإدارة',
    publicRegistration: 'التسجيل العام',
    publicRegistrationDesc: 'السماح للمستخدمين الجدد بتسجيل حسابات',
  },
  zh: {
    dashboard: '仪表板',
    content: '内容',
    users: '用户',
    settings: '设置',
    logout: '登出',
    welcome: '欢迎回来',
    totalEdits: '总编辑',
    lastUpdated: '最后更新',
    activeUsers: '活跃用户',
    pendingReviews: '待审核',
    heroSection: '英雄部分',
    aboutSection: '关于部分',
    servicesSection: '服务部分',
    contactSection: '联系部分',
    footerSection: '页脚部分',
    save: '保存',
    cancel: '取消',
    edit: '编辑',
    delete: '删除',
    name: '名称',
    email: '电子邮件',
    role: '角色',
    lastLogin: '最后登录',
    title: '标题',
    description: '描述',
    image: '图片',
    uploadImage: '上传图片',
    contactInfo: '联系信息',
    socialLinks: '社交链接',
    phone: '电话',
    address: '地址',
    facebook: '脸书',
    twitter: '推特',
    instagram: 'Instagram',
    linkedin: '领英',
    login: '登录',
    password: '密码',
    rememberMe: '记住我',
    // Dashboard specific
    welcomeToDashboard: '到您的管理仪表板',
    recentActivity: '最近活动',
    contentOverview: '内容概览',
    systemStatus: '系统状态',
    fromLastMonth: '较上月',
    thisWeek: '本周',
    updatedHeroSection: '更新了英雄部分',
    modifiedAboutSection: '修改了关于部分',
    addedNewService: '添加了新服务',
    updatedContactInfo: '更新了联系信息',
    hoursAgo: '小时前',
    daysAgo: '天前',
    by: '由',
    admin: '管理员',
    editor: '编辑',
    heroSections: '英雄部分',
    aboutSections: '关于部分',
    services: '服务',
    projects: '项目',
    database: '数据库',
    healthy: '健康',
    apiStatus: 'API状态',
    online: '在线',
    storage: '存储',
    used: '已用',
    cache: '缓存',
    optimized: '已优化',
    // Login page
    loginToDashboard: '访问仪表板',
    loggingIn: '正在登录...',
    invalidCredentials: '凭据无效',
    errorOccurred: '发生错误。请重试。',
    protectedArea: '受保护的管理区域 - 仅限授权访问',
    // Content page
    manageContent: '管理多语言网站内容',
    contentLanguage: '内容语言',
    selectLanguage: '选择要编辑的语言',
    lastEdited: '最后编辑',
    subtitle: '副标题',
    buttonText: '按钮文本',
    enterTitle: '输入标题...',
    enterSubtitle: '输入副标题...',
    enterDescription: '输入描述...',
    enterButtonText: '输入按钮文本...',
    noImageUploaded: '未上传图片',
    upload: '上传',
    remove: '删除',
    unsavedChanges: '未保存的更改',
    saveChanges: '保存更改',
    changes: '更改',
    // Users page
    manageUsers: '管理用户账户和权限',
    addUser: '添加用户',
    totalUsers: '总用户数',
    admins: '管理员',
    searchUsers: '搜索用户...',
    filters: '筛选',
    actions: '操作',
    status: '状态',
    active: '活跃',
    inactive: '不活跃',
    noUsersFound: '未找到用户',
    viewer: '查看者',
    // Settings page
    manageSettings: '管理应用设置和偏好',
    updateContactInfo: '更新您的业务联系信息',
    manageSocialMedia: '管理您的社交媒体资料',
    globalSettings: '全局设置',
    configureSystem: '配置系统级偏好',
    maintenanceMode: '维护模式',
    maintenanceModeDesc: '启用维护模式以阻止用户访问',
    emailNotifications: '电子邮件通知',
    emailNotificationsDesc: '接收重要事件的电子邮件通知',
    twoFactorAuth: '双因素认证',
    twoFactorAuthDesc: '要求所有管理员用户使用2FA',
    publicRegistration: '公开注册',
    publicRegistrationDesc: '允许新用户注册账户',
  },
};

const AdminLanguageContext = createContext<AdminLanguageContextType | undefined>(undefined);

export function AdminLanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const stored = localStorage.getItem('adminLanguage') as Language;
    if (stored && ['en', 'ar', 'zh'].includes(stored)) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('adminLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <AdminLanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </AdminLanguageContext.Provider>
  );
}

export function useAdminLanguage() {
  const context = useContext(AdminLanguageContext);
  if (context === undefined) {
    throw new Error('useAdminLanguage must be used within an AdminLanguageProvider');
  }
  return context;
}
